import day11
import unittest

class Day11(unittest.TestCase):
    def test_part1(self):
        lines = """
...#......
.......#..
#.........
..........
......#...
.#........
.........#
..........
.......#..
#...#.....
        """
        self.assertEqual(day11.solvePart1(lines.splitlines()), 374)
    def test_part2_1(self):
        lines = """
...#......
.......#..
#.........
..........
......#...
.#........
.........#
..........
.......#..
#...#.....
        """
        self.assertEqual(day11.solve_it(lines.splitlines(), 10), 1030)
    def test_part2_2(self):
        lines = """
...#......
.......#..
#.........
..........
......#...
.#........
.........#
..........
.......#..
#...#.....
        """
        self.assertEqual(day11.solve_it(lines.splitlines(), 100), 8410)

if __name__ == '__main__':
    unittest.main()
